# Generated by Django 3.0.3 on 2020-03-10 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('link', models.CharField(max_length=256)),
                ('image', models.CharField(max_length=256)),
                ('image_embedded', models.BinaryField()),
                ('mallName', models.CharField(max_length=256)),
                ('lprice', models.CharField(blank=True, max_length=64)),
                ('hprice', models.CharField(blank=True, max_length=64)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Category')),
            ],
        ),
    ]
