# Generated by Django 3.0.3 on 2020-03-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_embedded',
            field=models.TextField(default=''),
        ),
    ]
