# Generated by Django 3.0.3 on 2020-03-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_product_image_embedded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_embedded',
            field=models.BinaryField(),
        ),
    ]
